[book]
authors = ["thy1037"]
language = "en"
multilingual = false
src = "src"
title = "动手学 rust-libp2p"

[rust]
edition = "2021"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/rustedu/libp2p-slides"
